### ISSUE TITLE
Add Bi-Directional to character data page

### ISSUE THREAD

**Issue by NeatNit** [apocop/unicodedecode#40]
The main Unicode Decode page displays a Bi-Directional column. This is visible in the screenshot in the Readme.

This information is missing from the character data page (for example: https://unicodedecode.com/character/05D0 for א). I believe this is a mistake, since all other columns from the decode page are represented in the character data page, and it seems odd that this information would be omitted intentionally.

PS I love this tool, it's super useful!

**Comment by danieljdorado** [comment]
Thanks @NeatNit, you're right, this is an oversight.  I'll get this fixed this week. Glad to hear you find the site super useful!

**Comment by NeatNit** [comment]
Thanks for fixing this! Coincidentally I *just* found another bug (writing the issue on it right now) before I even noticed you were active here. That one should be an easy fix too, so you might want to hold on before you publish the change on the website :)

**Comment by danieljdorado** [comment]
haha, too late. It's already pushed to prod
